server:
  port: 1101
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system  
    username: root
    password: megha123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
#schema generation
    generate-ddl: true
    hibernate:
      ddl-auto: update
  application:
    name: BACKEND 
  main:
    banner-mode: off